// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1k8v54kJvK9wBC9EdZnV5ekcLa4j-u6Y',
    appId: '1:831459053347:web:dc0229764bcdc485858696',
    messagingSenderId: '831459053347',
    projectId: 'friute-b7390',
    authDomain: 'friute-b7390.firebaseapp.com',
    storageBucket: 'friute-b7390.firebasestorage.app',
    measurementId: 'G-VTB3316Z5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3sMRmlx4wJK2Lh4ra2Hb1c6AZGzfYeZ8',
    appId: '1:831459053347:android:0ea8645d233a6c72858696',
    messagingSenderId: '831459053347',
    projectId: 'friute-b7390',
    storageBucket: 'friute-b7390.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD3dlKxAS7vvD8TVKVCAS4-SsxaG73C0s',
    appId: '1:831459053347:ios:e90ee9ba29749baa858696',
    messagingSenderId: '831459053347',
    projectId: 'friute-b7390',
    storageBucket: 'friute-b7390.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD3dlKxAS7vvD8TVKVCAS4-SsxaG73C0s',
    appId: '1:831459053347:ios:e90ee9ba29749baa858696',
    messagingSenderId: '831459053347',
    projectId: 'friute-b7390',
    storageBucket: 'friute-b7390.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1k8v54kJvK9wBC9EdZnV5ekcLa4j-u6Y',
    appId: '1:831459053347:web:abb919912a322dfa858696',
    messagingSenderId: '831459053347',
    projectId: 'friute-b7390',
    authDomain: 'friute-b7390.firebaseapp.com',
    storageBucket: 'friute-b7390.firebasestorage.app',
    measurementId: 'G-G5HDSSN001',
  );
}
